### ISSUE TITLE
Is YCDB_API_query.R missing?

### ISSUE THREAD

**Issue by tswwe** [maseology/sHydrology_analysis#1]
Dear repo owner(s):
I downloaded your code and tried to run but got failure. After reviewing the source code, I believe the reason is that **the latest commit is missing a file *YCDB_API_query.R*,** which is introduced by line 28: `source("functions/YCDB_API_query.R", local = TRUE)` in another file *pkg/package.R*. 
I have tried to replace line 28 in *pkg/package.R* to `source("functions/HYDAT_query.R", local = TRUE)` because the *HYDAT_query.R* file seems like a copy or old version of *YCDB_API_query.R* based on historical commits. I also tried to extract *YCDB_API_query.R* file from historical commits. However, these attempts don't work because both *HYDAT_query.R* and old version of  *YCDB_API_query.R* file are lack of a function *qStaAgg* called by */pkg/collect_hydrograph.R* (line 8, specifically).
If the code runs well on your machine, I guess you can whether just remove the line 'YCDB_API_query.R` in *.gitignore* file, or correct the *HYDAT_query.R* file, and then re-push the commit to fix this problem.
Greetings,
thXnder

**Comment by maseology** [comment]
Hi there, sorry for the delay and thank you for noticing this.  My latest upload was sloppy.  This shiny app I have made "general" in the sense that it is used operationally (via APIs) at oakridgeswater.ca, and can also hit a 3rd party DB and I've used HYDAT as an example (and is the sole query set can provide publicly).

qStaAgg() is an attempt to "aggregate" data from 2 periods of record at effectively the same location.  This way, a longer time series can be obtained at specific locations.  I have no way of doing this with the HYDAT database, so I've added a dummy finction to prevent the error.
