### ISSUE TITLE
Error: URL invalid.

### ISSUE THREAD

**Issue by cug-xyx** [maseology/sHydrology_analysis#2]
Dear repo owner(s):

**Two questions:**

# Q1:

Still can't find YCDB_API_query.R file, is it that we don't need this file?

# Q2:

I replaced the `functions/YCDB_API_query.R` in the source.R file with the `functions/HYDAT_query.R` file. Showing `Error: URL invalid.` after running shinyApp.

I would be grateful if you could answer my question!

**Comment by maseology** [comment]
My appologies, I havn't tested with HYDAT in awhile; the repo has been updated. Let me know if you find anything else, thanks.

**Comment by cug-xyx** [comment]
Thank you very much for your help.
Best Wishes




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "maseology/sHydrology_analysis"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年5月26日(星期四) 晚上10:33
***@***.***&gt;;
抄送:&nbsp;"- ***@***.******@***.***&gt;;
主题:&nbsp;Re: [maseology/sHydrology_analysis] Error: URL invalid. (Issue #2)





 
My appologies, I havn't tested with HYDAT in awhile; the repo has been updated. Let me know if you find anything else, thanks.
